# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sql_controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sql_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sql_controller.proto\x12\x15\x63om.example.clearcard\"@\n\nSqlRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"\x19\n\x06Schema\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\"\x14\n\x03Row\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\t\"\x98\x01\n\x08SqlChunk\x12-\n\x06schema\x18\x01 \x01(\x0b\x32\x1d.com.example.clearcard.Schema\x12(\n\x04rows\x18\x02 \x03(\x0b\x32\x1a.com.example.clearcard.Row\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x0c\n\x04last\x18\x05 \x01(\x08\x32\\\n\rSqlController\x12K\n\x03Run\x12!.com.example.clearcard.SqlRequest\x1a\x1f.com.example.clearcard.SqlChunk0\x01\x42-\n\x15\x63om.example.clearcardB\x12SqlControllerProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sql_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.example.clearcardB\022SqlControllerProtoP\001'
  _globals['_SQLREQUEST']._serialized_start=47
  _globals['_SQLREQUEST']._serialized_end=111
  _globals['_SCHEMA']._serialized_start=113
  _globals['_SCHEMA']._serialized_end=138
  _globals['_ROW']._serialized_start=140
  _globals['_ROW']._serialized_end=160
  _globals['_SQLCHUNK']._serialized_start=163
  _globals['_SQLCHUNK']._serialized_end=315
  _globals['_SQLCONTROLLER']._serialized_start=317
  _globals['_SQLCONTROLLER']._serialized_end=409
# @@protoc_insertion_point(module_scope)
